
ALTER TABLE smestuvanja
    ADD COLUMN kapacitet    INTEGER,
    ADD COLUMN adresa       VARCHAR(500),
    ADD COLUMN wifi         BOOLEAN DEFAULT FALSE,
    ADD COLUMN spa          BOOLEAN DEFAULT FALSE,
    ADD COLUMN bazen        BOOLEAN DEFAULT FALSE,
    ADD COLUMN balkon       BOOLEAN DEFAULT FALSE,
    ADD COLUMN parking      BOOLEAN DEFAULT FALSE,
    ADD COLUMN kujna        BOOLEAN DEFAULT FALSE,
    ADD COLUMN klima        BOOLEAN DEFAULT FALSE,
    ADD COLUMN ljubimci     BOOLEAN DEFAULT FALSE;