-- V5__update_accommodation_amenities_and_addresses.sql

UPDATE smestuvanja SET
                       adresa = 'Беровско Езеро бб, Берово, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 1;
UPDATE smestuvanja SET
                       adresa = 'с. Ѕвегор, Делчево, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 2;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 3;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 4;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 5;
UPDATE smestuvanja SET
                       adresa = 'Широк Сокак бб, Битола, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 6;
UPDATE smestuvanja SET
                       adresa = 'Пехчево, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 7;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 8;
UPDATE smestuvanja SET
                       adresa = 'Маврово Национален Парк, Маврово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 9;
UPDATE smestuvanja SET
                       adresa = 'Маврово Национален Парк, Маврово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 10;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 11;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 12;
UPDATE smestuvanja SET
                       adresa = 'Ул. 2-ри Август бб, Гевгелија, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 13;
UPDATE smestuvanja SET
                       adresa = 'Кратово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 14;
UPDATE smestuvanja SET
                       adresa = 'Широк Сокак бб, Битола, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 15;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 16;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 17;
UPDATE smestuvanja SET
                       adresa = 'Вевчани, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 18;
UPDATE smestuvanja SET
                       adresa = 'Беровско Езеро бб, Берово, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 19;
UPDATE smestuvanja SET
                       adresa = 'Ул. Маршал Тито бб, Крива Паланка, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 20;
UPDATE smestuvanja SET
                       adresa = 'с. Ѕвегор, Делчево, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 21;
UPDATE smestuvanja SET
                       adresa = 'Крајбрежна бб, Нов Дојран, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 22;
UPDATE smestuvanja SET
                       adresa = 'Попова Шапка, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 23;
UPDATE smestuvanja SET
                       adresa = 'Попова Шапка, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 24;
UPDATE smestuvanja SET
                       adresa = 'Ул. Маршал Тито бб, Кичево, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 25;
UPDATE smestuvanja SET
                       adresa = 'Ул. Панко Брашнар бб, Велес, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 26;
UPDATE smestuvanja SET
                       adresa = 'бул. Октомври бб, Куманово, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 27;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 28;
UPDATE smestuvanja SET
                       adresa = 'Беровско Езеро бб, Берово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 29;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 30;
UPDATE smestuvanja SET
                       adresa = 'Ул. Маршал Тито бб, Кичево, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 31;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 32;
UPDATE smestuvanja SET
                       adresa = 'Крајбрежна бб, Нов Дојран, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 33;
UPDATE smestuvanja SET
                       adresa = 'Преспа, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 34;
UPDATE smestuvanja SET
                       adresa = 'Србија, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 35;
UPDATE smestuvanja SET
                       adresa = 'Грција, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 36;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 37;
UPDATE smestuvanja SET
                       adresa = 'Кочани/Пониква, Македонија',
                       kapacitet = 20,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 38;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 39;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 40;
UPDATE smestuvanja SET
                       adresa = 'бул. Октомври бб, Куманово, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 41;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 42;
UPDATE smestuvanja SET
                       adresa = 'Беровско Езеро бб, Берово, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 43;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 44;
UPDATE smestuvanja SET
                       adresa = 'Вевчани, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 45;
UPDATE smestuvanja SET
                       adresa = 'Ул. Панко Брашнар бб, Велес, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 46;
UPDATE smestuvanja SET
                       adresa = 'Ул. Панко Брашнар бб, Велес, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 47;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 48;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 49;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 50;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 51;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = TRUE,
                       spa = TRUE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 52;
UPDATE smestuvanja SET
                       adresa = 'Широк Сокак бб, Битола, Македонија',
                       kapacitet = 6,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 53;
UPDATE smestuvanja SET
                       adresa = 'Маврово Национален Парк, Маврово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 54;
UPDATE smestuvanja SET
                       adresa = 'бул. Партизански Одреди бб, Скопје, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 55;
UPDATE smestuvanja SET
                       adresa = 'Беровско Езеро бб, Берово, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 56;
UPDATE smestuvanja SET
                       adresa = 'Ул. Питу Гули бб, Крушево, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 57;
UPDATE smestuvanja SET
                       adresa = 'Ул. Питу Гули бб, Крушево, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 58;
UPDATE smestuvanja SET
                       adresa = 'Македонски Брод, Македонија',
                       kapacitet = 8,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 59;
UPDATE smestuvanja SET
                       adresa = 'Македонски Брод, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 60;
UPDATE smestuvanja SET
                       adresa = 'Кеј Македонија бб, Охрид, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 61;
UPDATE smestuvanja SET
                       adresa = 'Ул. 7 Март бб, Струга, Македонија',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = FALSE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 62;
UPDATE smestuvanja SET
                       adresa = 'Грција, Грција',
                       kapacitet = 4,
                       wifi = TRUE,
                       bazen = FALSE,
                       spa = FALSE,
                       balkon = FALSE,
                       parking = FALSE,
                       kujna = TRUE,
                       klima = FALSE,
                       ljubimci = FALSE
WHERE id = 63;